/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { StaleWhileRevalidate } from 'workbox-strategies'
import { BroadcastUpdatePlugin } from 'workbox-broadcast-update'

declare const self: ServiceWorkerGlobalScope

// ---- Tiny IndexedDB helper (no deps, works in SW + window) ----
const DB_NAME = 'clavus-push'
const STORE = 'kv'

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1)
    req.onupgradeneeded = () => req.result.createObjectStore(STORE)
    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
}

async function idbSet(key: string, value: unknown): Promise<void> {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE, 'readwrite')
    tx.objectStore(STORE).put(value, key)
    tx.oncomplete = () => { db.close(); resolve() }
    tx.onerror = () => { db.close(); reject(tx.error) }
  })
}

// Take control immediately when updated
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Clean old caches on update
cleanupOutdatedCaches()

// Precache all assets generated by the build (production only)
// In dev mode __WB_MANIFEST is empty, but we still need to call it for workbox
precacheAndRoute(self.__WB_MANIFEST)

// Runtime caching. This is the layer that actually fires in dev mode (the
// Capacitor shell points at the dev server through Cloudflare), where the
// precache manifest above is empty. Without it, every JS chunk goes over the
// network on every cold start and the Home conversations render visibly late.
//
// Strategy: same-origin GETs are served from cache instantly, then refreshed
// in the background. The next load picks up any change — when the change is
// a new app build, the SW update path triggers an explicit reload via
// onNeedRefresh in main.tsx.
//
// Excluded: API + HMR/WS endpoints. Caching those would either return stale
// data or break the dev tooling.
const RUNTIME_CACHE_BYPASS = [
  /^\/api\//,
  /^\/v1\//,
  /^\/marksense\//,
  /^\/elevenlabs\//,
  /^\/openrouter\//,
  /^\/hermes\//,
  /^\/responses\//,
  /^\/realtime\//,
  /^\/push\//,
  /^\/transcripts\//,
  /^\/desktop-dictation\//,
  /^\/documents\//,
  /^\/workspace\//,
  /^\/compose\//,
  /^\/upload\//,
  // Vite dev tooling — HMR, react-refresh, the optimizer's runtime probes.
  /^\/@/,
  /^\/__vite/,
  /^\/dashboard-logger\.js/,
  /\bhot-update\b/,
]

function isRuntimeCacheable(url: URL): boolean {
  if (url.origin !== self.location.origin) return false
  for (const pattern of RUNTIME_CACHE_BYPASS) {
    if (pattern.test(url.pathname)) return false
  }
  return true
}

// Navigation (HTML) cache. BroadcastUpdatePlugin posts a message to all
// clients when the fetched HTML differs from the cached copy — this is how we
// detect new deploys in dev mode, where `sw.js` itself doesn't change between
// Vite restarts. main.tsx listens for that message and triggers updateSW().
const navigationStrategy = new StaleWhileRevalidate({
  cacheName: 'clavus-navigation',
  plugins: [new BroadcastUpdatePlugin()],
})

registerRoute(
  ({ url, request }) => request.mode === 'navigate' && isRuntimeCacheable(url),
  navigationStrategy,
)

// Asset cache. New deploys ship new chunk URLs in the new HTML, so cache
// hits only on unchanged URLs — no extra update detection needed here.
const runtimeStrategy = new StaleWhileRevalidate({ cacheName: 'clavus-runtime' })

registerRoute(
  ({ url, request }) => request.method === 'GET' && request.mode !== 'navigate' && isRuntimeCacheable(url),
  runtimeStrategy,
)

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return

  const data = event.data.json() as {
    title?: string
    body?: string
    threadId?: string
  }

  const title = data.title || 'Clavus'
  const options: NotificationOptions = {
    body: data.body || '',
    icon: '/icon-192.svg',
    badge: '/icon-192.svg',
    data: { threadId: data.threadId },
    tag: data.threadId || 'clavus-notification',
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click — iOS-proof deep linking
// iOS ignores openWindow URL params and postMessage races app startup.
// Solution: persist threadId in IndexedDB, app reads it on boot/focus.
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const threadId = event.notification.data?.threadId as string | undefined
  const targetUrl = threadId ? `/?thread=${threadId}` : '/'

  event.waitUntil((async () => {
    // Always persist to IndexedDB (bulletproof for cold start)
    if (threadId) {
      await idbSet('pendingThread', { threadId, ts: Date.now() })
    }

    const clientList = await self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    })

    // Tier A: existing client — try navigate + focus + postMessage
    for (const client of clientList) {
      try {
        const wc = client as WindowClient
        if ('navigate' in wc) await wc.navigate(targetUrl)
        if ('focus' in wc) await wc.focus()
        // Also postMessage as fast-path (may work if app is warm)
        wc.postMessage({ type: 'navigate-thread', threadId })
        return
      } catch {
        // fall through to cold-start path
      }
    }

    // Tier B: cold start — just open the app (iOS may ignore URL, that's OK)
    try {
      await self.clients.openWindow(targetUrl)
    } catch {
      await self.clients.openWindow('/')
    }
  })())
})
