/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

// ---- Tiny IndexedDB helper (no deps, works in SW + window) ----
const DB_NAME = 'clavus-push'
const STORE = 'kv'

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1)
    req.onupgradeneeded = () => req.result.createObjectStore(STORE)
    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
}

async function idbSet(key: string, value: unknown): Promise<void> {
  const db = await openDB()
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE, 'readwrite')
    tx.objectStore(STORE).put(value, key)
    tx.oncomplete = () => { db.close(); resolve() }
    tx.onerror = () => { db.close(); reject(tx.error) }
  })
}

// Take control immediately when updated
self.addEventListener('install', () => self.skipWaiting())
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// Clean old caches on update
cleanupOutdatedCaches()

// Precache all assets generated by the build (production only)
// In dev mode __WB_MANIFEST is empty, but we still need to call it for workbox
precacheAndRoute(self.__WB_MANIFEST)

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return

  const data = event.data.json() as {
    title?: string
    body?: string
    threadId?: string
  }

  const title = data.title || 'Clavus'
  const options: NotificationOptions = {
    body: data.body || '',
    icon: '/icon-192.svg',
    badge: '/icon-192.svg',
    data: { threadId: data.threadId },
    tag: data.threadId || 'clavus-notification',
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click — iOS-proof deep linking
// iOS ignores openWindow URL params and postMessage races app startup.
// Solution: persist threadId in IndexedDB, app reads it on boot/focus.
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const threadId = event.notification.data?.threadId as string | undefined
  const targetUrl = threadId ? `/?thread=${threadId}` : '/'

  event.waitUntil((async () => {
    // Always persist to IndexedDB (bulletproof for cold start)
    if (threadId) {
      await idbSet('pendingThread', { threadId, ts: Date.now() })
    }

    const clientList = await self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    })

    // Tier A: existing client — try navigate + focus + postMessage
    for (const client of clientList) {
      try {
        const wc = client as WindowClient
        if ('navigate' in wc) await wc.navigate(targetUrl)
        if ('focus' in wc) await wc.focus()
        // Also postMessage as fast-path (may work if app is warm)
        wc.postMessage({ type: 'navigate-thread', threadId })
        return
      } catch {
        // fall through to cold-start path
      }
    }

    // Tier B: cold start — just open the app (iOS may ignore URL, that's OK)
    try {
      await self.clients.openWindow(targetUrl)
    } catch {
      await self.clients.openWindow('/')
    }
  })())
})
