/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching'

declare const self: ServiceWorkerGlobalScope

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST)

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return

  const data = event.data.json() as {
    title?: string
    body?: string
    threadId?: string
  }

  const title = data.title || 'Clavus'
  const options: NotificationOptions = {
    body: data.body || '',
    icon: '/icon-192.svg',
    badge: '/icon-192.svg',
    data: { threadId: data.threadId },
    tag: data.threadId || 'clavus-notification',
  }

  event.waitUntil(self.registration.showNotification(title, options))
})

// Notification click — open/focus app and navigate to thread
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const threadId = event.notification.data?.threadId as string | undefined
  const urlPath = threadId ? `/?thread=${threadId}` : '/'

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Focus existing window if available
      for (const client of clientList) {
        if ('focus' in client) {
          client.focus()
          client.postMessage({ type: 'navigate-thread', threadId })
          return
        }
      }
      // Otherwise open a new window
      return self.clients.openWindow(urlPath)
    }),
  )
})
